name: Github Workflow Example

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest


        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print environment
              run: echo "${{ secrets.APP_ENV }}"
            
            - name: Provide permission and execute app.sh
              run: chmod +x app.sh &&  ./app.sh

            - name: Provide permission and execute test.sh
              run: chmod +x test.sh && ./test.sh

