name : Github worklow

on:
    push:
        branches:
            - main

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:

            - name: Cloning the repo
              uses: actions/checkout@v4

            - name: Enviornment checking
              run: echo $"{{secrets.APP_ENV}}"

            - name: Provide the permission and execute app.sh
              run: chmod +x app.sh && ./app.sh

            - name: Provide the permission and execute test.sh
              run: chmod +x test.sh && ./test.sh

            